# Credit card fraud detection using LositicRegression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.tail(2)

Time        V1        V2        V3        V4        V5        V6  \
284805  172788.0 -0.240440  0.530483  0.702510  0.689799 -0.377961  0.623708   
284806  172792.0 -0.533413 -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9  ...       V21       V22       V23  \
284805 -0.686180  0.679145  0.392087  ...  0.265245  0.800049 -0.163298   
284806  1.577006 -0.414650  0.486180  ...  0.261057  0.643078  0.376777   

             V24       V25       V26       V27       V28  Amount  Class  
284805  0.123205 -0.569159  0.546668  0.108821  0.104533    10.0      0  
284806  0.008797 -0.473649 -0.818267 -0.002415  0.013649   217.0      0  

[2 rows x 31 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [5]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
# distribution of transaction
df['Class'].value_counts()          # this is unbalnce data set
                                    # 0 represent normal transaction
                                    # 1 represent fradulent transaction

0    284315
1       492
Name: Class, dtype: int64

In [7]:
## Get the Fraud and the normal dataset 

fraud = df[df['Class']==1]          # 0 represent normal transaction
normal = df[df['Class']==0]         # 1 represent fradulent transaction

In [8]:
print(fraud.shape,normal.shape)

(492, 31) (284315, 31)


In [9]:
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [10]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [11]:
# Compare the value for both Transaction
df.groupby('Class').mean()    # mean value of both transaction

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       88.291022  
1      122.211321  

[2 rows x 30 columns]

## under Sampling

In [12]:
# Build a sample containing similar distribution of normal transactiom and fraudulent transaction
# number of fraud transaction 492
normal_sample = normal.sample(n=492)

In [13]:
# concate two data frame
new_dataset = pd.concat([normal_sample, fraud], axis=0)  # axis 0 means add a rows, axis 1 means add a column

In [14]:
new_dataset.head()

Time        V1        V2        V3        V4        V5        V6  \
236762  148940.0  1.058547  0.213277 -0.818700  0.041770  0.405843 -0.279664   
18835    29805.0 -0.346495  0.476760  1.247987 -2.090632  0.113078 -0.528207   
57073    47740.0  1.149605 -0.167393  0.702724  1.274788  0.080164  1.709075   
22517    32287.0  0.944580  0.274386  0.462097  2.998025 -0.280952 -0.053634   
11368    19828.0 -0.693441  0.362902  2.651711 -1.749294 -0.288551 -0.201163   

              V7        V8        V9  ...       V21       V22       V23  \
236762 -0.022400 -0.973588  0.566417  ...  0.941691  0.482471 -0.167497   
18835   0.654555 -0.156159  0.834405  ... -0.220859 -0.339280 -0.266709   
57073  -0.628328  0.479320  0.979487  ... -0.450259 -0.794089 -0.097409   
22517  -0.054444  0.150561 -0.089019  ... -0.063515 -0.166803 -0.075253   
11368   0.310430 -0.067021  2.665408  ... -0.139206  0.151427 -0.333633   

             V24       V25       V26       V27       V28  Amount  Class  
236762  0.698548  0.123604  0.675629  0.169434  0.226509   12.36      0  
18835  -0.381824  0.128347 -0.187048  0.119850  0.107948    9.88      0  
57073  -1.328340  0.603814 -0.443677  0.092036  0.004671    2.00      0  
22517   0.287228  0.441795  0.084450  0.017735  0.054584   75.08      0  
11368   0.007430  0.367123 -0.810258 -0.071310 -0.157226   11.85      0  

[5 rows x 31 columns]

In [15]:
new_dataset.shape

(984, 31)

In [16]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [17]:
new_dataset.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      96120.016260  0.087724  0.113085 -0.046993 -0.022471 -0.028651   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.120719  0.047274  0.018595  0.005682  ... -0.028943 -0.042740   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.033512  0.025816  0.003794 -0.023419 -0.019436  0.015735 -0.016134   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       85.877663  
1      122.211321  

[2 rows x 30 columns]

##  Split the Data

In [18]:
X = new_dataset.drop(['Class'], axis =1)
y = new_dataset['Class']

In [19]:
print(X.shape,y.shape)

(984, 30) (984,)


## Split Train Test data

In [20]:
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 2)

## Model Training

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

 ## Evaluation

In [22]:
from sklearn.metrics import accuracy_score

# Accuracy score on train
X_train_Prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_Prediction, y_train)
training_data_accuracy

0.9313850063532402

In [23]:
# Accuracy score on test data
X_test_Prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_Prediction, y_test)
testing_data_accuracy

0.949238578680203

## Predict fraud or normal transaction

In [24]:
Transaction1= [44020,
-2.08019566589776,
-1.48145786974139,
0.516771646881197,
-1.16309689006059,
-0.589716551553122,
-0.754701097981268,
0.541694365012122,
0.402953320177984,
-1.40780838381479,
-0.576891930693835,
-1.1641846691172,
-0.804693074337633,
-1.20916533246826,
0.57679421783463,
-0.32589966933605,
-1.64247688006708,
0.548674167224613
,0.572972692935653,
-1.55608924427737,
0.17354815455573,
-0.0543162047972504,
-0.680976755665646,
0.518638011415891,
0.0587094108114146,
0.150325131444048,
0.946356573611898,
-0.20975570060728,
-0.143933188765623,
287.98]

In [25]:
Transaction1 = np.array([Transaction1])  # convert in array of prediction data
Transaction1

array([[ 4.40200000e+04, -2.08019567e+00, -1.48145787e+00,
         5.16771647e-01, -1.16309689e+00, -5.89716552e-01,
        -7.54701098e-01,  5.41694365e-01,  4.02953320e-01,
        -1.40780838e+00, -5.76891931e-01, -1.16418467e+00,
        -8.04693074e-01, -1.20916533e+00,  5.76794218e-01,
        -3.25899669e-01, -1.64247688e+00,  5.48674167e-01,
         5.72972693e-01, -1.55608924e+00,  1.73548155e-01,
        -5.43162048e-02, -6.80976756e-01,  5.18638011e-01,
         5.87094108e-02,  1.50325131e-01,  9.46356574e-01,
        -2.09755701e-01, -1.43933189e-01,  2.87980000e+02]])

In [26]:
Transaction1.ndim  # this is 3d array

2

In [31]:
Transaction1_ = Transaction1.reshape(1,30)  #convert array 3d o 2d
Transaction1_

array([[ 4.40200000e+04, -2.08019567e+00, -1.48145787e+00,
         5.16771647e-01, -1.16309689e+00, -5.89716552e-01,
        -7.54701098e-01,  5.41694365e-01,  4.02953320e-01,
        -1.40780838e+00, -5.76891931e-01, -1.16418467e+00,
        -8.04693074e-01, -1.20916533e+00,  5.76794218e-01,
        -3.25899669e-01, -1.64247688e+00,  5.48674167e-01,
         5.72972693e-01, -1.55608924e+00,  1.73548155e-01,
        -5.43162048e-02, -6.80976756e-01,  5.18638011e-01,
         5.87094108e-02,  1.50325131e-01,  9.46356574e-01,
        -2.09755701e-01, -1.43933189e-01,  2.87980000e+02]])

In [32]:
model.predict(Transaction1_)

array([0], dtype=int64)

In [33]:
pred = model.predict(Transaction1_)

In [34]:
if pred[0] == 0:
    print('normal Transaction')
else:
    print('Fraud Transaction')

normal Transaction
